// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv8IFJg0RVN0URUSs76llaaJV1zxEdDpo',
    appId: '1:664786675879:web:d04f926c6d59b56dc31382',
    messagingSenderId: '664786675879',
    projectId: 'merath-alnabi-984b6',
    authDomain: 'merath-alnabi-984b6.firebaseapp.com',
    storageBucket: 'merath-alnabi-984b6.appspot.com',
    measurementId: 'G-39M08XQVPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZAjO7NEC-cFEht1_QrBSaWkFvgR5zR0',
    appId: '1:664786675879:android:e29b96fe7d9005dac31382',
    messagingSenderId: '664786675879',
    projectId: 'merath-alnabi-984b6',
    storageBucket: 'merath-alnabi-984b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyPBIrDsxB2yfxOXC180g63PgjJf5Wu04',
    appId: '1:664786675879:ios:9230274ee727ecd9c31382',
    messagingSenderId: '664786675879',
    projectId: 'merath-alnabi-984b6',
    storageBucket: 'merath-alnabi-984b6.appspot.com',
    iosClientId:
        '664786675879-m5j8ur5hshk95armq011jfljacfeence.apps.googleusercontent.com',
    iosBundleId: 'com.arrawdah.meerath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyPBIrDsxB2yfxOXC180g63PgjJf5Wu04',
    appId: '1:664786675879:ios:9230274ee727ecd9c31382',
    messagingSenderId: '664786675879',
    projectId: 'merath-alnabi-984b6',
    storageBucket: 'merath-alnabi-984b6.appspot.com',
    iosClientId:
        '664786675879-m5j8ur5hshk95armq011jfljacfeence.apps.googleusercontent.com',
    iosBundleId: 'com.arrawdah.meerath',
  );
}
